// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxnf4v0rMiS5_a7J80D_BQxtNASZF6ryg',
    appId: '1:475750243783:web:29672bb978a2cb9688cde2',
    messagingSenderId: '475750243783',
    projectId: 'ai-chatbot-be649',
    authDomain: 'ai-chatbot-be649.firebaseapp.com',
    storageBucket: 'ai-chatbot-be649.firebasestorage.app',
    measurementId: 'G-NRLMVP33BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhiAQrdULYCmffBNM6ndWbdrMWG8SvNXc',
    appId: '1:475750243783:android:94306094f2572a5788cde2',
    messagingSenderId: '475750243783',
    projectId: 'ai-chatbot-be649',
    storageBucket: 'ai-chatbot-be649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdXMJo8pn2y5h2QpSM-jOeG_-ChP5qlcQ',
    appId: '1:475750243783:ios:3f0e84d99385d28b88cde2',
    messagingSenderId: '475750243783',
    projectId: 'ai-chatbot-be649',
    storageBucket: 'ai-chatbot-be649.firebasestorage.app',
    iosBundleId: 'com.example.aichatbot',
  );
}
